pipeline {
    agent any

    environment {
        DOCKER_IMAGE ='sathiyanarayananr/aws-devops-app'
    }

    stages {
        stage('checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test') {
            steps {
                sh 'python3 --version'
                sh '.venv/bin/pip install -r app/requirements.txt'
                sh '.venv/bin/python -m pytest -v'
            }
        }
    
        stage('Docker Build'){
            steps {
                sh ' docker build -f docker/Dockerfile -t "$DOCKER_IMAGE" .'
            }
        }

        stage('Docker push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId : 'dockerhub-credentials',
                        usernameVariable : 'DOCKER_USERNAME',
                        passwordVariable : 'DOCKER_PASSWORD'
                    )
                ]){ sh '''
                echo "$DOCKER_PASSWORD" | docker login \
                -u "$DOCKER_USERNAME" \
                --password-stdin
                docker push $DOCKER_IMAGE

                docker logout
                '''
            }

            
        }  
    }

    stage('Deploy') {
            steps {
                sh '''
                    ansible-playbook \
                        -i Ansible/inventory \
                        Ansible/deploy.yml
                '''
        }
    }


}
}